"""initial schema

Revision ID: f089c65eff0b
Revises: 
Create Date: 2026-09-21 14:29:33.632526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f089c65eff0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('checkin_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('registration_id', sa.String(length=64), nullable=False),
    sa.Column('event_url', sa.String(length=1000), nullable=False),
    sa.Column('sig', sa.String(length=64), nullable=False),
    sa.Column('exp', sa.DateTime(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('nft_claim_id', sa.String(length=128), nullable=True),
    sa.Column('nft_contract', sa.String(length=128), nullable=True),
    sa.Column('nft_token_id', sa.String(length=128), nullable=True),
    sa.Column('nft_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkin_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_tokens_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_tokens_registration_id'), ['registration_id'], unique=False)

    op.create_table('service_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('telegram_id', sa.String(length=32), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_entries',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('points_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_entries_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_entries_user_id'), ['user_id'], unique=False)

    op.create_table('tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subscription_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_subscription_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_token_hash'))

    op.drop_table('tokens')
    with op.batch_alter_table('points_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_points_entries_reason'))
        batch_op.drop_index(batch_op.f('ix_points_entries_created_at'))

    op.drop_table('points_entries')
    op.drop_table('webhook_subscriptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('service_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_keys_key_hash'))

    op.drop_table('service_keys')
    with op.batch_alter_table('checkin_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_tokens_registration_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_tokens_event_id'))

    op.drop_table('checkin_tokens')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
